### ISSUE TITLE
Dynamic Load - How far back does it look?

### ISSUE THREAD

**Issue by abnersnell** [everettsouthwick/Eraserr#48]
For the Dynamic Load feature, how far back does it go? I have a library I would like to clean up but seems to only be detecting shows with episodes watched today?

**Comment by everettsouthwick** [comment]
Dynamic Load uses the current Plex sessions as its source. It is triggered by people watching something on Plex. It will then analyze that show to see if it qualifies for deletion and if it needs to have files loaded ahead of where the current user is watching. It looks like when I refactored the code I removed the "age based" deletion respecting "episodes to keep". I am going to fix that so age based deletion will keep the first X number of episodes of a show upon deleting if you have dynamic load enabled

**Comment by abnersnell** [comment]
Would it be possible to apply Dynamic Load to the entire TV library in an effort to realize the space benefit sooner?  Sort of like a catch-up since we haven't had this wonderful program until now. :-)

**Comment by everettsouthwick** [comment]
#49 makes it so if you have dynamic load enabled then any "age based" deletions will instead unmonitor the series instead of deleting it and keep the first "episodes_to_load" of a series, whether it is continuing series or ended. You could use this to set the sonarr watched/unwatched thresholds to clean up old media and get your library in a thin state to fully utilize the dynamic loading potential. I would recommend caution because this does not take into account if people are currently watching a show, it just looks at the age and deletes it regardless of user watch history. I may change that in the future, but that will be quite a large undertaking and I'm not going to commit to doing that at this time.
